# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the FML version. This is currently 2.
loaderVersion = "${loader_version_range}" #mandatory

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license = "${mod_license}"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId = "chromabreak" #mandatory

# The version number of the mod
version = "${mod_version}" #mandatory

# A display name for the mod
displayName = "ChromaBreak" #mandatory

# A text field displayed in the mod UI
authors = "Sunsmilktea" #optional

# The description text for the mod (multi line!) (#mandatory)
description = '''A mod that focuses on colorful rendering effects, entity customization, and chroma-themed visual enhancements.'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config = "chromabreak.mixins.json"

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.chromabreak]] #optional
# the modid of the dependency
modId = "neoforge" #mandatory
# The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
# 'required' requires the mod to exist, 'optional' does not
# 'incompatible' will prevent the game from loading when the mod exists, and 'discouraged' will show a warning
type = "required" #mandatory
# The version range of the dependency
versionRange = "[${neo_version},)" #mandatory
# An ordering relationship for the dependency.
# BEFORE - This mod is loaded BEFORE the dependency
# AFTER - This mod is loaded AFTER the dependency
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side = "BOTH"

# Optional dependency on KubeJS - enables scripting support for ChromaBreak
[[dependencies.chromabreak]]
modId = "kubejs"
type = "optional"
versionRange = "[2101,)"
ordering = "NONE"
side = "BOTH"

# Optional dependency on Lychee - enables additional recipe types or compatibility
[[dependencies.chromabreak]]
modId = "lychee"
type = "optional"
versionRange = "[6.0,)"
ordering = "NONE"
side = "BOTH"

# Optional dependency on Kiwi (if you use any Kiwi features directly)
[[dependencies.chromabreak]]
modId = "kiwi"
type = "optional"
versionRange = "[15.0,)"
ordering = "NONE"
side = "BOTH"